apiVersion: apps/v1
kind: Deployment
metadata:
  name: nesamani-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nesamani
  template:
    metadata:
      labels:
        app: nesamani
        tier: backend
    spec:
      containers:
      - image: gcr.io/nesamani-sol21/nesamani-backend@sha256:87182b1244b048b3f16490c4113d2769ad15b6e2ac68922d2ee01cc21af6d79c
        name: application
        ports:
        - name: flask
          protocol: TCP
          containerPort: 5000
        
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nesamani-backend
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
