apiVersion: v1
kind: PersistentVolume
metadata:
  name: nesamani-pv
  labels:
    type: local
    app: nesamani
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nesamani-pv-claim-new
  labels:
    app: nesamani
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
