apiVersion: apps/v1
kind: Deployment
metadata:
  name: nesamani-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: devagastya0/nesamani_backend:v1.0.1
        name: application
        ports:
        - containerPort: 5000
